services:
  - type: web
    name: flask-calendar-api
    runtime: python
    buildCommand: ""
    startCommand: gunicorn api:app
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        sync: false
